/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.inbot.escodegen

import org.gradle.testkit.runner.GradleRunner
import java.io.File
import kotlin.test.Test

class EsKotlinCodeGenPluginFunctionalTest {
    @Test fun `can run task`() {
        // Setup the test build
        val projectDir = File("build/functionalTest")
        projectDir.mkdirs()
        projectDir.resolve("settings.gradle").writeText("")
        projectDir.resolve("build.gradle").writeText("""
            plugins {
                id('io.inbot.search.codegen')
            }
            
            codegen {
                output = "/Users/jillesvangurp/git/es-kotlin-wrapper-client/client/build/generatedcode"
            }
        """)

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("codegen")
        runner.withProjectDir(projectDir)
        runner.build();

        // Verify the result
//        assertTrue(result.output.contains("Hello from plugin 'com.jillesvangurp.escodegen.generateExtensionFunctions'"))
    }
}
