/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.inbot.escodegen

import org.gradle.api.Plugin
import org.gradle.api.Project

class EsKotlinCodeGenPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("generateExtensionFunctions") { task ->
            task.doLast {
                val esCodeGenerator = EsCodeGenerator()
                esCodeGenerator.generateCode()
            }
        }
    }
}
